In [20]:
import pandas

In [35]:
ATC_projections = pandas.read_csv('ATC_projections.csv')
ATC_values = pandas.read_csv('ATC-auction-values.csv')
ATC_projections_simplified = ATC_projections.drop(columns = ['Name','G', 'AB', 'H', '1B', '2B', '3B', 'BB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'CS', 'BB%', 'IBB', 'K%', 'BB/K', 'ISO', 'BABIP', 'AVG', 'InterSD', 'InterSK', 'IntraSD', 'Spd', 'UBR', 'wSB', 'wRC', 'wRAA', 'BsR', 'Fld', 'Off', 'Def', 'WAR', 
                                                            'wRC+', 'Team', 'ADP'])
ATC_values_simplified = ATC_values.drop(columns = ['Team', 'ADP', 'PA', 'mRBI', 'mR', 'mSB', 'mHR', 'mOBP', 'mSLG', 'PTS', 'aPOS'])
joined_ATC = ATC_values_simplified.merge(ATC_projections_simplified, left_on='PlayerId', right_on='PlayerId')

In [45]:
final_ATC = joined_ATC[['Name', 'POS', 'Dollars', 'PA', 'HR', 'R', 'RBI', 'SB', 'OBP', 'SLG', 'OPS','wOBA']]
final_ATC.sort_values(by=['Dollars'])
final_ATC = final_ATC.head(300)
final_ATC

,Name,POS,Dollars,PA,HR,R,RBI,SB,OBP,SLG,OPS,wOBA
0,Ronald Acuna Jr.,OF,65.740293,658.845,35.27820,119.8990,92.9023,51.559100,0.402163,0.566034,0.968197,0.409484
1,Aaron Judge,OF/DH,53.506417,600.231,43.69530,99.8445,106.1640,6.396060,0.394749,0.585756,0.980505,0.408204
2,Juan Soto,OF,52.786478,664.032,36.69160,104.4990,100.0750,10.621900,0.419920,0.544450,0.964370,0.408576
3,Yordan Alvarez,OF/DH,49.486261,598.905,38.62180,95.3077,106.5430,0.727507,0.397501,0.593411,0.990911,0.413988
4,Shohei Ohtani,P/DH,49.149141,608.746,37.93070,101.0920,98.7215,18.521500,0.384617,0.572624,0.957240,0.399017
...,...,...,...,...,...,...,...,...,...,...,...,...
295,Randal Grichuk,OF,-20.752015,278.285,9.19115,32.7711,33.5885,1.276320,0.298867,0.419144,0.718011,0.308623
296,Mauricio Dubon,2B/OF,-20.797825,332.440,6.74594,41.1691,34.1083,4.649490,0.299706,0.380935,0.680641,0.295232
297,Joey Wiemer,OF,-20.902877,269.655,8.44656,32.1999,30.5180,8.262090,0.300151,0.387182,0.687332,0.299717
298,Mike Tauchman,OF,-20.912187,288.247,5.42783,37.5054,28.7520,4.908880,0.340648,0.366091,0.706739,0.314503
299,Victor Robles,OF,-20.967275,353.147,5.42731,40.4665,28.7051,14.917900,0.313134,0.352391,0.665524,0.294792

In [71]:
final_ATC.to_csv('RyanBatters2024.csv')

PITCHERS BELOW

In [40]:
ATC_pitcher_projections = pandas.read_csv('ATC_pitcherprojections.csv')
ATC_pitcher_projections_simplified = ATC_pitcher_projections.drop(columns = ['Team', 'W', 'L', 'G', 'GS', 'TBF', 'H', 'R', 'ER', 'HR', 'BB', 'IBB', 'HBP', 'K/BB', 'HR/9', 'K%', 'BB%','AVG', 'BABIP', 'LOB%',
       'GB%', 'HR/FB', 'FIP', 'WAR', 'RA9-WAR',  'InterSD', 'InterSK',
       'IntraSD',])
ATC_pitcher_values = pandas.read_csv('ATC_pitchervalues.csv')
ATC_pitcher_values_simplified = ATC_pitcher_values.drop(columns = ['Name','Team','ADP', 'IP', 'mSV', 'mERA', 'mWHIP', 'mSO',
       'mHLD', 'mQS', 'PTS', 'aPOS'])
joined_ATC_pitchers = ATC_pitcher_values_simplified.merge(ATC_pitcher_projections_simplified, left_on='PlayerId', right_on='PlayerId')

In [44]:
final_ATC_pitchers = joined_ATC_pitchers[['Name', 'POS', 'Dollars', 'IP','ERA', 'WHIP',  'K/9', 'QS','SV', 'HLD', 'K-BB%']]
final_ATC_pitchers.sort_values(by=['Dollars'])

final_ATC_pitchers = final_ATC_pitchers.head(300)
final_ATC_pitchers

,Name,POS,Dollars,IP,ERA,WHIP,K/9,QS,SV,HLD,K-BB%
0,Spencer Strider,SP,34.567932,178.5300,3.38505,1.08112,12.63890,14.76700,0.000000,0.000000,0.267050
1,Gerrit Cole,SP,25.905061,170.1380,3.53343,1.09821,10.05420,14.82300,0.000000,0.000000,0.214828
2,Zack Wheeler,SP,25.745156,184.8610,3.51957,1.11811,9.34911,16.23510,0.000000,0.000000,0.197239
3,George Kirby,SP,25.703458,181.2740,3.56805,1.09001,8.48299,15.08320,0.000000,0.000000,0.197061
4,Kevin Gausman,SP,24.512213,178.8830,3.42950,1.14911,10.47580,15.35420,0.000000,0.000000,0.221099
...,...,...,...,...,...,...,...,...,...,...,...
295,Connor Brogdon,RP,-8.862269,45.7194,4.24783,1.31270,8.98361,0.00000,0.253939,5.549440,0.147823
296,Michael Tonkin,RP,-8.864867,45.9938,4.33929,1.25447,9.03271,0.00000,0.112532,3.423890,0.156124
297,Ranger SuÃ¡rez,SP,-8.865147,148.0980,4.01234,1.33583,7.92310,10.30260,0.199879,0.000000,0.120220
298,Jakob Junis,SP,-8.872276,99.0794,4.40768,1.28416,8.71362,3.44112,0.209156,0.822545,0.164621
299,John King,RP,-8.970692,49.4907,3.95265,1.40523,5.85326,0.00000,0.508744,10.114200,0.082639

In [67]:
PL_rankings = pandas.read_csv('PitcherList Rankings 2024.csv', encoding='latin-1')
Eno_ranks = pandas.read_csv('EnoRanks.csv')

In [68]:
updated_pitchers =final_ATC_pitchers.merge(PL_rankings, how = 'left', left_on= 'Name', right_on= 'Name')
updated_pitchers = updated_pitchers.merge(Eno_ranks, how = 'left', left_on= 'Name', right_on= 'Name')
updated_pitchers.head(50)

,Name,POS,Dollars,IP,ERA,WHIP,K/9,QS,SV,HLD,K-BB%,PL Rank,Eno
0,Spencer Strider,SP,34.567932,178.5300,3.38505,1.08112,12.63890,14.76700,0.000000,0.000000,0.267050,1.0,1.0
1,Gerrit Cole,SP,25.905061,170.1380,3.53343,1.09821,10.05420,14.82300,0.000000,0.000000,0.214828,NaN,3.0
2,Zack Wheeler,SP,25.745156,184.8610,3.51957,1.11811,9.34911,16.23510,0.000000,0.000000,0.197239,3.0,4.0
3,George Kirby,SP,25.703458,181.2740,3.56805,1.09001,8.48299,15.08320,0.000000,0.000000,0.197061,6.0,5.0
4,Kevin Gausman,SP,24.512213,178.8830,3.42950,1.14911,10.47580,15.35420,0.000000,0.000000,0.221099,7.0,6.0
5,Corbin Burnes,SP,23.551290,185.9890,3.52987,1.14015,9.67062,15.90590,0.000000,0.000000,0.188460,2.0,2.0
6,Pablo LÃ³pez,SP,23.118306,183.0220,3.52111,1.14084,9.93767,14.79330,0.000000,0.000000,0.205261,4.0,11.0
7,Tarik Skubal,SP,22.584274,155.7070,3.44111,1.11859,10.28490,11.95630,0.000000,0.000000,0.216728,10.0,14.0
8,Logan Webb,SP,22.516487,193.0610,3.41695,1.16008,8.03704,16.48950,0.000000,0.000000,0.166121,8.0,9.0
9,Luis Castillo,SP,21.864097,188.2030,3.53585,1.15272,9.55026,15.35890,0.000000,0.000000,0.185346,NaN,7.0
10,Tyler Glasnow,SP,21.175516,139.5990,3.49544,1.10730,11.37570,10.90890,0.000000,0.000000,0.236641,11.0,10.0
11,Zach Eflin,SP,20.372880,165.4910,3.63597,1.10601,8.73246,12.94580,0.003008,0.000000,0.196485,17.0,18.0
12,Framber Valdez,SP,19.412875,189.3980,3.39395,1.20182,8.95412,16.73810,0.000000,0.000000,0.161219,22.0,21.0
13,Edwin DÃ­az,RP,17.935339,61.9520,2.71248,1.04962,14.06570,0.00000,33.048700,0.745309,0.304076,NaN,NaN
14,Freddy Peralta,SP,17.682360,161.6020,3.70130,1.14078,10.81750,12.49740,0.000000,0.000000,0.209961,20.0,17.0
15,Max Fried,SP,17.587012,162.1430,3.40246,1.17638,8.64071,13.34830,0.000000,0.000000,0.173933,13.0,23.0
16,Zac Gallen,SP,17.416397,185.5380,3.68718,1.15804,9.24047,14.77490,0.000000,0.000000,0.184386,12.0,13.0
17,Yoshinobu Yamamoto,SP,17.261342,165.8360,3.68598,1.12676,9.55680,10.55170,0.000000,0.000000,0.195813,16.0,8.0
18,Aaron Nola,SP,16.669993,186.3290,3.89572,1.12475,9.43005,13.79290,0.000000,0.000000,0.204528,14.0,22.0
19,Logan Gilbert,SP,16.152343,183.9630,3.81539,1.13846,8.96616,13.99590,0.000000,0.000000,0.188844,31.0,12.0
20,Joe Musgrove,SP,14.828575,153.1640,3.64968,1.15553,8.95442,13.02360,0.000000,0.000000,0.179228,NaN,24.0
21,Jhoan Duran,RP,14.430464,64.0787,2.81150,1.13265,12.01920,0.00000,32.785200,1.965950,0.241111,NaN,NaN
22,Emmanuel Clase,RP,12.903362,66.0865,2.99775,1.10734,8.80287,0.00000,34.099800,0.930835,0.185554,NaN,NaN
23,Pete Fairbanks,RP,12.581407,53.5876,2.87102,1.10514,12.48230,0.00000,29.156300,2.996390,0.247368,NaN,NaN
24,AndrÃ©s MuÃ±oz,RP,12.574145,58.4123,2.94599,1.12757,12.02090,0.00000,28.432000,4.185420,0.236456,NaN,NaN
25,Mason Miller,SP,12.171787,60.0654,3.35093,1.15894,11.59930,0.24272,14.537300,7.579970,0.213336,NaN,NaN
26,Joe Ryan,SP,11.756403,163.3490,3.99960,1.13652,9.98271,11.65820,0.000000,0.000000,0.208741,30.0,40.0
27,Josh Hader,RP,11.754336,59.0476,3.08246,1.15929,13.04630,0.00000,34.233600,2.138930,0.244117,NaN,NaN
28,Grayson Rodriguez,SP,11.533230,159.7500,3.71023,1.18149,9.68795,10.73760,0.000000,0.000000,0.181495,18.0,16.0
29,Evan Phillips,RP,11.357171,61.8167,3.20771,1.11104,10.13970,0.00000,28.121400,4.480380,0.203462,NaN,NaN
30,Bobby Miller,SP,11.079837,152.0580,3.82417,1.14845,8.84128,10.31920,0.000000,0.000000,0.172076,15.0,15.0
31,Jason Adam,RP,10.631317,56.6827,3.30669,1.09449,10.83880,0.00000,10.702600,13.836100,0.212215,NaN,NaN
32,Devin Williams,RP,10.586038,57.0031,2.87091,1.16599,12.70140,0.00000,28.643200,1.665380,0.229536,NaN,NaN
33,Chris Sale,SP,10.442190,129.9580,3.81776,1.15109,10.58990,8.76138,0.000000,0.000000,0.215128,25.0,34.0
34,Bryan Abreu,RP,10.381369,63.2419,3.02285,1.18767,12.09180,0.00000,3.209350,17.351200,0.218679,NaN,NaN
35,Blake Snell,SP,10.122125,156.3170,3.49707,1.26595,11.40790,12.64150,0.000000,0.131387,0.186211,32.0,19.0
36,JesÃºs Luzardo,SP,10.096931,168.2960,3.77667,1.20862,10.21460,13.26950,0.000000,0.000000,0.194689,34.0,29.0
37,Raisel Iglesias,RP,9.836342,60.6220,3.33239,1.12420,10.80040,0.00000,30.716200,2.322630,0.232708,NaN,NaN
38,Michael King,SP,9.643975,139.7650,3.59006,1.20465,9.89969,8.09305,0.235696,0.801195,0.183615,29.0,28.0
39,Shane Bieber,SP,9.375577,166.2460,3.77778,1.19803,8.51673,13.78240,0.000000,0.000000,0.166986,49.0,36.0
40,Ryan Helsley,RP,9.171080,60.6776,3.13329,1.17378,11.79040,0.00000,25.742300,3.819370,0.215736,NaN,NaN
41,Eury PÃ©rez,SP,9.128509,141.3750,3.83321,1.17273,10.26220,9.16456,0.000000,0.000000,0.197549,19.0,20.0
42,Ryan Pressly,RP,8.708032,61.5318,3.39245,1.12752,10.01850,0.00000,4.817430,15.850400,0.207407,NaN,NaN
43,JosÃ© Alvarado,RP,8.575851,63.1847,3.09410,1.24299,12.31440,0.00000,23.480100,7.282670,0.214699,NaN,NaN
44,David Bednar,RP,8.527354,60.9957,3.23837,1.16727,10.72500,0.00000,29.386000,2.196510,0.210587,NaN,NaN
45,Tanner Bibee,SP,8.463743,164.3220,3.75691,1.20715,9.18934,11.62670,0.000000,0.000000,0.172692,36.0,43.0
46,Justin Steele,SP,8.217659,170.7170,3.66711,1.23199,8.74694,13.33090,0.000000,0.000000,0.162032,NaN,25.0
47,Matt Strahm,SP/RP,8.175477,65.3546,3.64842,1.14143,10.60080,0.00000,1.434500,9.439620,0.218684,NaN,NaN
48,Tanner Scott,RP,8.069589,66.3007,3.19923,1.21716,11.89110,0.00000,26.538500,3.787650,0.212461,NaN,NaN
49,Hunter Harvey,RP,7.544416,59.9635,3.54857,1.15151,10.00450,0.00000,12.985900,13.027000,0.201975,NaN,NaN

In [70]:
updated_pitchers.to_csv('RyanPitchers2024.csv')

In [31]:
BatX_projections = pandas.read_csv('BatX_projections.csv')

In [32]:
BatX_projections.head()

,Name,Team,G,PA,AB,H,1B,2B,3B,HR,...,BsR,Fld,Off,Def,WAR,ADP,InterSD,InterSK,IntraSD,PlayerId
0,Ronald AcuÃ±a Jr.,ATL,147,659,567,181,104,37,2,38,...,2.023480,5.03,55.909587,-1.977301,7.61561,1.00,NaN,NaN,NaN,18401
1,Mookie Betts,LAD,149,661,567,163,92,36,3,32,...,-0.851487,1.04,37.871009,3.863316,6.40663,5.00,NaN,NaN,NaN,13611
2,Aaron Judge,NYY,138,600,495,138,68,25,1,45,...,-1.038960,-4.98,50.031371,-8.107678,6.21410,11.37,NaN,NaN,NaN,15640
3,Juan Soto,NYY,153,664,531,147,82,27,2,36,...,-1.148100,-0.81,49.440711,-9.930907,6.18955,10.69,NaN,NaN,NaN,20123
4,Fernando Tatis Jr.,SDP,148,647,570,162,89,33,4,36,...,1.738100,4.78,39.388751,-2.050000,5.91945,7.95,NaN,NaN,NaN,19709

In [20]:
BatX_values = pandas.read_csv('BatX-auction-values.csv')

In [21]:
BatX_values.head()

,Name,Team,POS,ADP,PA,mRBI,mR,mSB,mHR,mOBP,mSLG,PTS,aPOS,Dollars,PlayerId
0,Ronald Acuna Jr.,ATL,OF,1.00,658.845,6.217697,11.841516,11.748658,7.039571,10.728669,10.928456,58.504566,14.333611,73.838177,18401
1,Shohei Ohtani,LAD,P/DH,12.66,608.746,6.849761,7.575178,3.723072,7.243515,7.598277,9.612245,42.602048,13.089649,56.691697,19755
2,Aaron Judge,NYY,OF/DH,11.37,600.231,8.162092,5.653330,-1.157579,9.949581,8.465430,10.096974,41.169828,14.333611,56.503439,15640
3,Fernando Tatis Jr.,SDP,OF,7.95,646.629,6.166505,7.077689,5.929712,6.090506,3.575208,7.165973,36.005593,14.333611,51.339204,19709
4,Juan Soto,NYY,OF,10.69,664.032,5.000607,7.332747,-0.292833,5.953599,11.832337,6.051138,35.877593,14.333611,51.211204,20123

In [22]:
ATC_values.head()

,Name,Team,POS,ADP,PA,mRBI,mR,mSB,mHR,mOBP,mSLG,PTS,aPOS,Dollars,PlayerId
0,Ronald Acuna Jr.,ATL,OF,1.00,658.845,4.143094,10.302812,11.929877,5.767331,9.642439,9.361783,51.147335,13.592958,65.740293,18401
1,Aaron Judge,NYY,OF/DH,11.37,600.231,7.454055,5.448967,-1.378222,9.876361,7.789933,9.722366,38.913459,13.592958,53.506417,15640
2,Juan Soto,NYY,OF,10.69,664.032,5.933854,6.575514,-0.133011,6.457307,12.386843,6.973013,38.193520,13.592958,52.786478,20123
3,Yordan Alvarez,HOU,OF/DH,16.42,598.905,7.548604,4.350899,-3.048563,7.399600,8.141682,10.501079,34.893303,13.592958,49.486261,19556
4,Shohei Ohtani,LAD,P/DH,12.66,608.746,5.595944,5.750846,2.194758,7.062213,6.500771,9.046742,36.151273,11.997868,49.149141,19755